### ISSUE TITLE
Can't use 'Function' as a name here

### ISSUE THREAD

**Issue by jiajialaixi** [Tencent-RTC/TRTC_Flutter#56]
![1661410125911](https://user-images.githubusercontent.com/20548416/186594640-373c231f-2e47-440f-905c-409e9b3ddc4b.png)

![image](https://user-images.githubusercontent.com/20548416/186596973-6b17a717-5bff-448c-a723-ebf6088ef735.png)

tencent_trtc_cloud 包在flutter 3.1.0 以上版本 报错 

以下是解决方案
![image](https://user-images.githubusercontent.com/20548416/186596541-c1c3737e-36d1-487a-a848-c9a0bc7c85e8.png)

请尽快更新

**Comment by c1avie** [comment]
建议先使用3.0.5及一下稳定版flutter版本

**Comment by c1avie** [comment]
2.3.7以上版本已经解决

**Comment by lan2000** [comment]
> 2.3.7以上版本已经解决

什么时候更新tencent_trtc_cloud_professional，5个月没更新了
