### ISSUE TITLE
tencent_trtc_cloud: 2.3.9  异常触发 onFirstVideoFrame

### ISSUE THREAD

**Issue by lan2000** [Tencent-RTC/TRTC_Flutter#60]
【当前现象】：升级到tencent_trtc_cloud: 2.3.9之后，只要加入的房间（房间里面有其他人开启摄像头），其他用户在房间里面，并开启摄像头，我进入房间，没有使用“startRemoteView（）”或“startRoteSubStreamView（）”，因为我已经屏蔽相关代码，但是trtcCloud.registerListener也监听到 onFirstVideoFrame 事件。

【机型】：华为nova6 4g
【之前版本有无此问题】：2.3.9之前没有，2.3.9有
【是否必现】：必出现
【复现方法】：其他用户提前进入视频房间，并开启摄像头。然后我再进房间。
【日志或者描述、截图】：
[LiteAV_C_20221014.zip](https://github.com/LiteAVSDK/TRTC_Flutter/files/10131193/LiteAV_C_20221014.zip)

**Comment by iveshzf** [comment]
We have fixed this issue in the new version
