### ISSUE TITLE
onTrtcListener同一状态会同时执行N+次

### ISSUE THREAD

**Issue by xiejianghua** [Tencent-RTC/TRTC_Flutter#62]
【当前现象】：onTrtcListener同一状态会同时执行N+次
【SDKAppID】：1400780037
【房间号】: 1
【useID】：1598236147035189249
【问题时间段】：2023-01-03 09:00~12:00
【机型】：和机型无关
【之前版本有无此问题】：  tencent_trtc_cloud: ^2.4.1
【是否必现】：必现
【复现方法】：两个手机TRTC_APP_SCENE_VOICE_CHATROOM ，语音聊天室，一个用户反复进出房间。
[【日志或者描述、截图】：
<img width="756" alt="截屏2023-01-03 11 08 35" src="https://user-images.githubusercontent.com/16914221/210301044-4666f66e-2161-4a46-b4c0-5797078d3bb9.png">
<img width="514" alt="截屏2023-01-03 11 09 08" src="https://user-images.githubusercontent.com/16914221/210301057-a1ee3299-defc-47cc-9c24-59a492c9ccf5.png">
<img width="282" alt="截屏2023-01-03 11 09 34" src="https://user-images.githubusercontent.com/16914221/210301002-c600e879-fb35-4faa-921e-0fd3028d9f03.png">
<img width="758" alt="截屏2023-01-03 10 50 04" src="https://user-images.githubusercontent.com/16914221/210301065-a5a20139-8a7e-4e67-a94d-00c81c649720.png">
<img width="1062" alt="截屏2023-01-03 10 48 45" src="https://user-images.githubusercontent.com/16914221/210301075-d82fc23c-bd88-4fc1-9a97-fd02be8e211c.png">

**Comment by xiejianghua** [comment]
<img width="282" alt="截屏2023-01-03 11 09 34" src="https://user-images.githubusercontent.com/16914221/210301002-c600e879-fb35-4faa-921e-0fd3028d9f03.png">

**Comment by iveshzf** [comment]
We have fixed this issue in the new version
