### ISSUE TITLE
請問如何創建房間後如何可以解散房間？

### ISSUE THREAD

**Issue by chris-yeung** [Tencent-RTC/TRTC_Flutter#73]
請問如何創建房間後如何可以解散房間？

TRTCCloud 裏面好像沒有 這個功能？

**Comment by iveshzf** [comment]
TRTC will automatically disband the room when the last person exits. If you need to actively disband the room, you can implement the relevant logic yourself or call our server interface.
https://trtc.io/document/34269?product=rtcengine&menulabel=serverfeaturesapis
