### ISSUE TITLE
[web] 升级到2.8.6 提示 Error: Dart library 'dart:ffi' is not available on this platform.

### ISSUE THREAD

**Issue by mvity** [Tencent-RTC/TRTC_Flutter#94]
[web] 升级到2.8.6 提示 Error: Dart library 'dart:ffi' is not available on this platform. 降级到2.8.2 正常 chrome 浏览器调试，项目无法运行

[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.24.0 on channel stable at /Users/vity/Code/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by iveshzf** [comment]
Thank you for reporting this issue. We have resolved this issue in version 2.8.8.
