### ISSUE TITLE
Android Gradle 8.3报错

### ISSUE THREAD

**Issue by zKidor** [Tencent-RTC/TRTC_Flutter#96]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':tencent_trtc_cloud'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

**Comment by iveshzf** [comment]
I apologize for the delay in addressing your issue. We have fixed the problem with Gradle 8.3 in the update on November 5. You can use version 2.9.2 or later to resolve this issue.

If you have any further questions or need assistance, feel free to ask!
